fix(SPSTRAT-731): add missing respin to resources.yaml
It is extracted from filename. It needn't be very portable
But it is needed for valid pushsource staging structure

+ tee /var/workdir/release/mock_pushsource_ls.txt
  import pkg_resources
Traceback (most recent call last):
  File "/usr/local/bin/pushsource-ls", line 10, in <module>
    sys.exit(main())
  File "pushsource/_impl/list_cmd.py", line 179, in main
    run(p)
  File "pushsource/_impl/list_cmd.py", line 144, in run
    for pushitem in source:
  File "pushsource/_impl/source.py", line 62, in __iter__
    for item in generator:
  File "pushsource/_impl/backend/staged/staged_source.py",
        line 183, in _push_items_for_topdir
    for pushitem in f.result():
  File "/usr/lib64/python3.9/concurrent/futures/_base.py",
        line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py",
         line 391, in __get_result
    raise self._exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py",
         line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "pushsource/_impl/backend/staged/staged_source.py",
         line 134, in _push_items_for_leafdir
    return self._FILE_TYPES[leafdir.file_type](leafdir=leafdir,
                                               metadata=metadata)
  File "pushsource/_impl/backend/staged/staged_base.py",
         line 46, in __mixin_push_items
    item = delegate(leafdir, metadata, entry)
  File "pushsource/_impl/backend/staged/staged_cloud.py",
         line 157, in __cloud_push_item
    self.__build_ami_push_item(raw, entry.path, image, leafdir.dest)
  File "pushsource/_impl/backend/staged/staged_cloud.py",
         line 32, in __build_ami_push_item
    build_info = KojiBuildInfo(
  File "<attrs generated methods
        pushsource._impl.model.base.KojiBuildInfo>",
         line 42, in __init__
  File "attr/validators.py", line 100, in __call__
    raise TypeError(
TypeError: ("'release' must be <class 'str'>
        (got None that is a <class 'NoneType'>).",
         Attribute(name='release', default=NOTHING,
                   validator=<instance_of validator
                              for type <class 'str'>>,
                   repr=True, eq=True, eq_key=None, order=True,
                   order_key=None, hash=None, init=True,
                   metadata=mappingproxy({}), type=<class 'str'>,
                   converter=None, kw_only=True, inherited=False,
                   on_setattr=None, alias='release'),
         <class 'str'>, None)

The patch also fixes extraction of architecture

[run-task] + echo '{
[run-task]   "api": "v1",
[run-task]   "resource": "CloudImage",
[run-task]   "description": "",
[run-task]   "build": {
[run-task]     "name": "TESTPRDOCUT",
[run-task]     "arch": "x86_64.raw",
[run-task]     "version": "1.3"
[run-task]   },
[run-task]   "images": [
[run-task]     {
[run-task]     "path": "test-product-amd-1.3-1732045201-x86_64.raw.gz",
[run-task]     "architecture": "x86_64.raw"
[run-task]     }
[run-task]   ],
[run-task]   "type": "AMI"
[run-task] }'
[run-task] + yq -P -I 4

Signed-off-by: Lukas Slebodnik <lslebodn@redhat.com>